# Generated by Django 4.2.30 on 2026-07-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('html_file', models.FileField(upload_to='animations/', verbose_name='Archivo HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Animación',
                'verbose_name_plural': 'Animaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
